version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_URI: ${MONGO_URI}
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend
  webserver:
    build:
      context: nginx
      dockerfile: Dockerfile
    image: webserver:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginxdata:/var/log/nginx
    depends_on:
      - fastapi
    networks:
      - frontend
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8009:80
    depends_on:
      - mongodb
    networks:
      - backend
    env_file:
      - .env

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
volumes:
  mongodbdata:
    driver: local
  nginxdata:
    driver: local
